// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refidomsa.Api.Data;

#nullable disable

namespace Refidomsa.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Refidomsa.Api.Models.Distribuidor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LimiteCredito")
                        .HasPrecision(28, 2)
                        .HasColumnType("decimal(28,2)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Rnc")
                        .IsUnique();

                    b.ToTable("Distribuidores", null, t =>
                        {
                            t.HasCheckConstraint("CK_Distribuidor_Credito", "[LimiteCredito] >= 0");
                        });
                });

            modelBuilder.Entity("Refidomsa.Api.Models.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DistribuidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("FechaCambioEstado")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FechaEntrega")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Total")
                        .HasPrecision(28, 2)
                        .HasColumnType("decimal(28,2)");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("DistribuidorId", "Estado");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Refidomsa.Api.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioPorGalon")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("Productos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Producto_Precio", "[PrecioPorGalon] > 0");
                        });
                });

            modelBuilder.Entity("Refidomsa.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DistribuidorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DistribuidorId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", null, t =>
                        {
                            t.HasCheckConstraint("CK_Usuario_RolDistribuidor", "([Rol] = 'Distribuidor' AND [DistribuidorId] IS NOT NULL) OR ([Rol] = 'Operador' AND [DistribuidorId] IS NULL)");
                        });
                });

            modelBuilder.Entity("Refidomsa.Api.Models.Pedido", b =>
                {
                    b.HasOne("Refidomsa.Api.Models.Distribuidor", null)
                        .WithMany()
                        .HasForeignKey("DistribuidorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Refidomsa.Api.Models.LineaPedido", "Lineas", b1 =>
                        {
                            b1.Property<Guid>("PedidoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Galones")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<string>("NombreProducto")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<decimal>("PrecioPorGalon")
                                .HasPrecision(18, 6)
                                .HasColumnType("decimal(18,6)");

                            b1.Property<decimal>("Subtotal")
                                .HasPrecision(28, 2)
                                .HasColumnType("decimal(28,2)");

                            b1.HasKey("PedidoId", "ProductoId");

                            b1.HasIndex("ProductoId");

                            b1.ToTable("LineasPedido", null, t =>
                                {
                                    t.HasCheckConstraint("CK_Linea_Galones", "[Galones] >= 500 AND [Galones] <= 9000");
                                });

                            b1.WithOwner()
                                .HasForeignKey("PedidoId");

                            b1.HasOne("Refidomsa.Api.Models.Producto", null)
                                .WithMany()
                                .HasForeignKey("ProductoId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();
                        });

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("Refidomsa.Api.Models.Usuario", b =>
                {
                    b.HasOne("Refidomsa.Api.Models.Distribuidor", null)
                        .WithMany()
                        .HasForeignKey("DistribuidorId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
